### ISSUE TITLE
Add Support For Multiple Monitors

### ISSUE THREAD

**Issue by FirstPotatoMan** [DDunda/LiveWallpaper#1]
Just thought that it would be kinda nice to see it work on more monitors as it currently only shows on one

**Comment by Fahrenheit** [comment]
+1 to this. It clips between two monitors for me. For some reason is chooses my small monitor to be the main that it shows it on. 
![image](https://user-images.githubusercontent.com/33299777/129619654-e17248e7-4bf4-46f3-83a9-d1c1bdb7eabf.png)

**Comment by DDunda** [comment]
Hi guys, thank you for mentioning this issue. I would really like to support multiple monitors, but unfortunately this program relies on an undocumented feature of Windows.

It uses 'WorkerW', a background window without an api or documentation, and I really have no idea how it interacts with multiple monitors. The way it was discovered was [explained here](https://www.codeproject.com/articles/856020/draw-behind-desktop-icons-in-windows-plus), but unfortunately I can't find much more information.

**Comment by DDunda** [comment]
Hello again and excuse me, I've made some changes lately to support multiple monitors. It turns out the WorkerW window spans every screen already, so I just needed to resize the canvas to fit every monitor. This required some procedural generation for the stars, but hopefully it's excusable that it doesn't match the original cave story texture exactly anymore
